version: 2
updates:
  - package-ecosystem: "cargo"
    directory: "/plug.app/rt"
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "rust"
    ignore:
      - dependency-name: "memmap2"
      - dependency-name: "derivative"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "ci"
